version: "3.8"
services:
  php74_csv_to_seeder:
    container_name: php74_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/Unit/CsvReaderTest.php

  php80_csv_to_seeder:
    container_name: php80_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/Unit/CsvReaderTest.php
    depends_on:
      - php74_csv_to_seeder

  php81_csv_to_seeder:
    container_name: php81_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/Unit/CsvReaderTest.php
    depends_on:
      - php80_csv_to_seeder

  php82_csv_to_seeder:
    container_name: php82_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/Unit/CsvReaderTest.php
    depends_on:
      - php81_csv_to_seeder