version: "3.8"
services:
  php74_csv_to_seeder:
    container_name: php74_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: ./.docker/command/test.sh

  php80_csv_to_seeder:
    container_name: php80_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: ./.docker/command/test.sh
    depends_on:
      - php74_csv_to_seeder

  php81_csv_to_seeder:
    container_name: php81_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: ./.docker/command/test.sh
    depends_on:
      - php80_csv_to_seeder

  php82_csv_to_seeder:
    container_name: php82_csv_to_seeder
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: ./.docker/command/test.sh
    depends_on:
      - php81_csv_to_seeder