name: PHPUnit test

on:
  pull_request:

jobs:
  phpunit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
      fail-fast: true
      max-parallel: 2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
        composer install
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libonig-dev libzip-dev unzip libxml2 zlib1g-dev
    - name: Run PHPUnit Test
      run: |
        vendor/bin/phpunit tests/Unit/CsvToSeederTest.php